// A homemade version of the game Wordle
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "The Knockoff Wordle",
      theme: ThemeData(primaryColor: Colors.black),
      home: const FirstScreen(),
    );
  }
}

class FirstScreen extends StatelessWidget {
  const FirstScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('The Knockoff Wordle')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'THE KNOCKOFF WORDLE',
              style: TextStyle(
                fontSize: 50,
                fontStyle: FontStyle.normal,
                fontWeight: FontWeight.w900,
                color: Colors.greenAccent,
              ),
            ),
            const SizedBox(height: 3),
            Text(
              'Created By: Hayden Garcia',
              style: TextStyle(
                fontSize: 8,
                fontStyle: FontStyle.italic,
                color: Colors.grey,
              ),
            ),
            TextSection(
              description:
                  'This is a home made version on the game "Wordle created by: Josh Wardle." '
                  'I created this new version of the game on September 24, 2025 '
                  'and have been calling this version the Knockoff Wordle '
                  'Please Enjoy!',
            ),
            SizedBox(height: 20),
            ElevatedButton(
              child: Text("How to Play"),
              onPressed: () async {
                final result = await Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const SecondScreen()),
                );

                if (result != null) print(result);
              },
            ),
          ],
        ),
      ),
    );
  }
}

class TextSection extends StatelessWidget {
  const TextSection({super.key, required this.description});

  final String description;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(32),
      child: Text(description, softWrap: true),
    );
  }
}

class SecondScreen extends StatelessWidget {
  const SecondScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('The Gist of it'),
        automaticallyImplyLeading: false,
        leading: ElevatedButton(
          onPressed: () {
            Navigator.pop(context, "Rules have been read");
          },
          child: Icon(Icons.arrow_back),
        ),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            TextSection(description: ''),
            Text(
              'How the Game Works!',
              style: TextStyle(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                color: Colors.green[100],
              ),
            ),
            SizedBox(height: 50),
            Text(
              '1. You have to guess a five letter word, and you get six tries.',
              style: TextStyle(
                fontSize: 10,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.brown,
              ),
            ),
            SizedBox(height: 7),
            Text(
              '2. If the word is not in the word list you will be prompted to input a new word.',
              style: TextStyle(
                fontSize: 10,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.brown,
              ),
            ),
            SizedBox(height: 7),
            Text(
              '3. If a tile turns yellow that tile means the character is correct, but placed in wrong spot.',
              style: TextStyle(
                fontSize: 10,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.brown,
              ),
            ),
            SizedBox(height: 7),
            Text(
              '4. If a tile turns grey that tile means the character is not used in the word.',
              style: TextStyle(
                fontSize: 10,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.brown,
              ),
            ),
            SizedBox(height: 7),
            Text(
              '5. If a tile turns green that tile means it is in the right spot and using the right character.',
              style: TextStyle(
                fontSize: 10,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.brown,
              ),
            ),
            SizedBox(height: 14),
            Text(
              'How to Win!',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Colors.red,
              ),
            ),
            SizedBox(height: 7),
            Text(
              'Get all the tiles to turn green before your guesses are up!',
              style: TextStyle(
                fontSize: 11,
                fontStyle: FontStyle.italic,
                fontWeight: FontWeight.normal,
                color: Colors.red,
              ),
            ),

            ElevatedButton(
              child: Text("Begin the game"),
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const ThirdScreen()),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class ThirdScreen extends StatefulWidget {
  const ThirdScreen({super.key});

  @override
  State<ThirdScreen> createState() {
    return _ThirdScreenState();
  }
}

class _ThirdScreenState extends State<ThirdScreen> {
  // the list of words
  List<String> _wordList = <String>[
    'ABACK',
    'ABASE',
    'ABATE',
    'ABBEY',
    'ABIDE',
    'ABOUT',
    'ABOVE',
    'ABYSS',
    'ACORN',
    'ACRID',
    'ACTOR',
    'ACUTE',
    'ADAGE',
    'ADAPT',
    'ADEPT',
    'ADMIN',
    'ADMIT',
    'ADOBE',
    'ADOPT',
    'ADORE',
    'ADULT',
    'AFFIX',
    'AFTER',
    'AGAIN',
    'AGAPE',
    'AGATE',
    'AGENT',
    'BADGE',
    'BADLY',
    'BAGEL',
    'BAKER',
    'BALER',
    'BALMY',
    'BALSA',
    'BANAL',
    'BANJO',
    'BARGE',
    'BASIC',
    'BASIN',
    'BASTE',
    'BATHE',
    'BATON',
    'BATTY',
    'BAWDY',
    'BAYOU',
    'BEACH',
    'BEADY',
    'BEAST',
    'BEAUT',
    'BEEFY',
    'BEGET',
    'BEGIN',
    'BEING',
    'BELCH',
    'CANNY',
    'CANOE',
    'CANON',
    'CAPER',
    'CARAT',
    'CARGO',
    'CAROL',
    'CARRY',
    'CARVE',
    'CATCH',
    'CATER',
    'CAULK',
    'CAUSE',
    'CEASE',
    'CEDAR',
    'CHAFE',
    'CHAIN',
    'CHAIR',
    'CHALK',
    'CHAMP',
    'CHANT',
    'CHAOS',
    'CHARD',
    'CHARM',
    'CHART',
    'CHASE',
    'DEBIT',
    'DEBUG',
    'DEBUT',
    'DECAL',
    'DECAY',
    'DECOY',
    'DECRY',
    'DEFER',
    'DEITY',
    'DELAY',
    'DELTA',
    'DELVE',
    'DENIM',
    'DEPOT',
    'DEPTH',
    'DETER',
    'DEVIL',
    'DIARY',
    'DICEY',
    'DIGIT',
    'DINER',
    'DINGO',
    'DINGY',
    'DIRGE',
    'DISCO',
    'DITTO',
    'DITTY',
    'EARTH',
    'EASEL',
    'EBONY',
    'EDICT',
    'EDIFY',
    'EGRET',
    'EJECT',
    'ELATE',
    'ELBOW',
    'ELDER',
    'ELITE',
    'ELOPE',
    'ELUDE',
    'EMAIL',
    'EMBER',
    'EMPTY',
    'ENACT',
    'ENDOW',
    'ENEMA',
    'ENJOY',
    'ENNUI',
    'ENSUE',
    'ENTER',
    'EPOCH',
    'EPOXY',
    'EQUAL',
    'EQUIP',
    'FAULT',
    'FAVOR',
    'FEAST',
    'FEIGN',
    'FERAL',
    'FERRY',
    'FETCH',
    'FEVER',
    'FEWER',
    'FIBER',
    'FIELD',
    'FIEND',
    'FIFTH',
    'FIFTY',
    'FILET',
    'FINAL',
    'FINCH',
    'FINER',
    'FIRST',
    'FISHY',
    'FIXER',
    'FJORD',
    'FLAIL',
    'FLAIR',
    'FLAKE',
    'FLAME',
    'FLANK',
    'FLARE',
    'GAMER',
    'GAWKY',
    'GECKO',
    'GEESE',
    'GENIE',
    'GENRE',
    'GHOST',
    'GHOUL',
    'GIANT',
    'GIDDY',
    'GIRTH',
    'GIVEN',
    'GLADE',
    'GLAND',
    'GLASS',
    'GLAZE',
    'GLEAM',
    'GLEAN',
    'GLIDE',
    'GLOAT',
    'GLOBE',
    'GLOOM',
    'GLORY',
    'GLOVE',
    'GLYPH',
    'GNASH',
    'GNOME',
    'GOFER',
    'HATCH',
    'HATER',
    'HAUNT',
    'HAVOC',
    'HAZEL',
    'HEADY',
    'HEARD',
    'HEART',
    'HAPPY',
    'HEAVE',
    'HEAVY',
    'HEFTY',
    'HEIST',
    'HELIX',
    'HELLO',
    'HENCE',
    'HERON',
    'HILLY',
    'HINGE',
    'HIPPO',
    'HITCH',
    'HOARD',
    'HOBBY',
    'HOMER',
    'HONEY',
    'HORDE',
    'HORSE',
    'IDLER',
    'IGLOO',
    'IMAGE',
    'IMBUE',
    'IMPEL',
    'INANE',
    'INBOX',
    'INCUR',
    'INDEX',
    'INDIE',
    'INEPT',
    'INERT',
    'INFER',
    'INLAY',
    'INNER',
    'INPUT',
    'INTER',
    'INTRO',
    'IONIC',
    'IRATE',
    'IRONY',
    'ISLET',
    'ISSUE',
    'ITCHY',
    'IVORY',
    'ICING',
    'JAZZY',
    'JELLY',
    'JERKY',
    'JEWEL',
    'JIFFY',
    'JOINT',
    'JOKER',
    'JOLLY',
    'JOUST',
    'JUDGE',
    'JUICE',
    'JUMPY',
    'KARMA',
    'KAYAK',
    'KAZOO',
    'KEBAB',
    'KEFIR',
    'KAHKI',
    'KIOSK',
    'KNACK',
    'KNAVE',
    'KNEAD',
    'KNEEL',
    'KNELL',
    'KNELT',
    'KNIFE',
    'KNOCK',
    'KNOLL',
    'KNOWN',
    'KOALA',
    'KRILL',
    'LABEL',
    'LABOR',
    'LADLE',
    'LAGER',
    'LANKY',
    'LAPEL',
    'LAPSE',
    'LARGE',
    'LARVA',
    'LASER',
    'LASSO',
    'LATER',
    'LATTE',
    'LAUGH',
    'LAYER',
    'LEAFY',
    'LEAKY',
    'LEAPT',
    'LEARN',
    'LEASE',
    'LEASH',
    'LEAST',
    'LEAVE',
    'LEDGE',
    'LEECH',
    'LEERY',
    'LEFTY',
    'LEGGY',
    'LEMON',
    'LEMUR',
    'LEVEL',
    'LIBEL',
    'LIGHT',
    'LILAC',
    'MAGMA',
    'MAIZE',
    'MAJOR',
    'MAMBO',
    'MANGA',
    'MANGO',
    'MANIA',
    'MANLY',
    'MAGIC',
    'MANOR',
    'MAPLE',
    'MARCH',
    'MARRY',
    'MARSH',
    'MASON',
    'MASSE',
    'MATCH',
    'MADLY',
    'MATEY',
    'MATTE',
    'MAUVE',
    'MAXIM',
    'MAYBE',
    'MAYOR',
    'MEALY',
    'MEANT',
    'MEDAL',
    'NANNY',
    'NASAL',
    'NASTY',
    'NATAL',
    'NAVAL',
    'NAVEL',
    'NEEDY',
    'NEIGH',
    'NERDY',
    'NERVE',
    'NERVY',
    'NEVER',
    'NICER',
    'NICHE',
    'NIGHT',
    'NINJA',
    'NINTH',
    'NOBLE',
    'NOISE',
    'NOISY',
    'NOMAD',
    'NORTH',
    'NOVEL',
    'NUDGE',
    'NURSE',
    'NYMPH',
    'OCCUR',
    'OCEAN',
    'OCTET',
    'ODDLY',
    'OFFAL',
    'OFFER',
    'OFTEN',
    'OLDER',
    'OLIVE',
    'OMEGA',
    'ONION',
    'ONSET',
    'OPERA',
    'ORDER',
    'ORGAN',
    'OTHER',
    'PAINT',
    'PANEL',
    'PANIC',
    'PAPAL',
    'PAPER',
    'PARER',
    'PARRY',
    'PARTY',
    'PASTA',
    'PATCH',
    'PATIO',
    'PATSY',
    'PATTY',
    'PAUSE',
    'PEACE',
    'PEACH',
    'PEARL',
    'PEDAL',
    'PENNE',
    'PERCH',
    'PERKY',
    'PESKY',
    'PETAL',
    'PETTY',
    'PHASE',
    'PHONE',
    'PHONY',
    'PHOTO',
    'PIANO',
    'PICKY',
    'QUIAL',
    'QUAKE',
    'QUALM',
    'QUART',
    'QUASH',
    'QUEEN',
    'QUERY',
    'QUEST',
    'QUEUE',
    'QUICK',
    'QUIET',
    'QUILL',
    'QUIRK',
    'QUITE',
    'QUOTA',
    'QUOTE',
    'RADIO',
    'RAINY',
    'RAISE',
    'RAMEN',
    'RANCH',
    'RANGE',
    'RAPID',
    'RATIO',
    'RATTY',
    'RAYON',
    'REACH',
    'REACT',
    'READY',
    'REALM',
    'REBEL',
    'REBUS',
    'REBUT',
    'RECAP',
    'RECUR',
    'REFER',
    'REGAL',
    'RELAX',
    'RELAY',
    'RELIC',
    'RENEW',
    'REPAY',
    'REPEL',
    'RERUN',
    'RESIN',
    'SASSY',
    'SAUCY',
    'SAUNA',
    'SAUTE',
    'SAVOR',
    'SAVVY',
    'SCALD',
    'SCALE',
    'SCANT',
    'SCARE',
    'SCARF',
    'SCENT',
    'SCOFF',
    'SCOLD',
    'SCONE',
    'SCOPE',
    'SCORE',
    'SCORN',
    'SCOUR',
    'SCOUT',
    'SCOWL',
    'SCRAM',
    'SCRAP',
    'SCRUB',
    'SCRUM',
    'SEDAN',
    'SEEDY',
    'TALLY',
    'TALON',
    'TANGY',
    'TAPER',
    'TAPIR',
    'TARDY',
    'TASTE',
    'TASTY',
    'TAUNT',
    'TAUPE',
    'TAWNY',
    'TEACH',
    'TEARY',
    'TEASE',
    'TEETH',
    'TEMPO',
    'TENOR',
    'TENTH',
    'TEPID',
    'TERSE',
    'THANK',
    'THEIR',
    'THEME',
    'THERE',
    'THREW',
    'THROB',
    'THROW',
    'UNDID',
    'UNDUE',
    'UNFED',
    'UNFIT',
    'UNIFY',
    'UNION',
    'UNITE',
    'UNLIT',
    'UNMET',
    'UNTIE',
    'UNTIL',
    'UNZIP',
    'UPPER',
    'UPSET',
    'URBAN',
    'USAGE',
    'USHER',
    'USING',
    'USUAL',
    'USURP',
    'UTTER',
    'UVULA',
    'VAGUE',
    'VALET',
    'VALID',
    'VALUE',
    'VAPID',
    'VAULT',
    'VENOM',
    'VERGE',
    'VERSE',
    'VERVE',
    'VIDEO',
    'VIGOR',
    'VILLA',
    'VINYL',
    'VIOLA',
    'VIRAL',
    'VISOR',
    'VITAL',
    'VIVID',
    'VIXEN',
    'VODKA',
    'VOICE',
    'VOILA',
    'VOTER',
    'VOUCH',
    'VYING',
    'WACKY',
    'WAFER',
    'WAGON',
    'WALTZ',
    'WASTE',
    'WATCH',
    'WATER',
    'WEARY',
    'WEDGE',
    'WEEDY',
    'WEIRD',
    'WHACK',
    'WHALE',
    'WHEAT',
    'WHEEL',
    'WHELP',
    'WHERE',
    'WHICH',
    'WHIFF',
    'WHILE',
    'WHINE',
    'WHINY',
    'WHIRL',
    'WHISK',
    'WHOLE',
    'WHOOP',
    'WHOSE',
    'WIDEN',
    'WIDTH',
    'WINCE',
    'WINDY',
    'WITCH',
    'WITTY',
    'YACHT',
    'YEARN',
    'YEAST',
    'YIELD',
    'YOUNG',
    'YOUTH',
    'ZEBRA',
    'ZESTY',
  ];
